### ISSUE TITLE
Minify the fontloader.js file

### ISSUE THREAD

**Issue by seangates** [eBay/ebay-font#16]
Create a minified version of the `fontloader.js` file to make it as small as possible. You know, for the sake of making it as small as possible. 😉

**Comment by RajaRamu** [comment]
@seangates - this file will be aggregated as part of page JS where lasso will take care of it.

**Comment by seangates** [comment]
From what I understand, "standalone" means you don't use it with the bundler. Isn't hat the case?

**Comment by senthilp** [comment]
@seangates We will apply uglify on the generated file.
