### ISSUE TITLE
Support font-display: swap

### ISSUE THREAD

**Issue by tonytopper** [eBay/ebay-font#42]
Would be nice if you could configure this to use font-display: swap or font-display: optional

**Comment by tonytopper** [comment]
Or font-display: fallback

**Comment by senthilp** [comment]
We are already using `font-display: optional` as the default. It is added in [Skin](https://github.com/eBay/skin/blob/09e0d98a1de338552d4ce0c19bfb50cea13b18dd/src/less/marketsans/marketsans.less#L16). We already disucced in detail about `swap` and `fallback`. Both can result in bad user expereince. Hence defaulted to `optional`
