### ISSUE TITLE
Safari 10 - Promise does not fire always with native document.fonts.load

### ISSUE THREAD

**Issue by RajaRamu** [eBay/ebay-font#6]
document.fonts.load and FontFace.prototype.load does not fire promise always. There is bug with safari 10. if its safari-10, use FontFaceObserver.

Bugs are listed below
 https://bugs.webkit.org/show_bug.cgi?id=165037
 https://bugs.webkit.org/show_bug.cgi?id=164902

**Comment by senthilp** [comment]
@RajaRamu Good observation. Instead of using direct Safari UA check, we should use some sort of feature check. We can discuss this.
